# Site settings
title: Dumitru Rareş
email: dumitru.rares14@gmail.com
url: https://dumitrurares14.github.io/
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "graphics programmer, engine developer, Rares, Rares Dumitru"
skills: "Graphics programmer - Engine Developer - Student"
meta_author: Dumitru Rareş

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2B303A #7C7C7C #80B3FF
  primary-rgb: "124,124,124" #"128,179,255"
  secondary: 7C7C7C #FD6E8A
  secondary-dark: 7C7C7C #A2122F

# Footer settings
footer:
  copyright: Dumitru Rareş
  location: Location
  credits: Credits
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/rares-dumitru-343a36214/
  - title: github
    url: https://github.com/dumitrurares14
  - title: play
    url: https://github.com/dumitrurares14

# Postal address (add as many lines as necessary)
address:
  - line: The Netherlands, Tilburg

# Credits content
credits: 'Student at Breda University of Applied Sciences'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
